repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    -   id: check-yaml
    -   id: check-json
    -   id: check-toml
    -   id: check-case-conflict
    -   id: end-of-file-fixer
        exclude: migrations/
    -   id: trailing-whitespace
    -   id: check-added-large-files  # 检查大文件的提交
        args: ["--maxkb=500"]
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.10
    hooks:
      - id: ruff
        args:
          - --fix
      - id: ruff-format
